version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    networks:
      - app-network
    ports:
      - 5672:5672
      - 15672:15672
  stock-service:
    image: deliverymuch/backend-challenge:stock-service
    networks:
      - app-network
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    restart: on-failure
  database:
    image: mongo
    restart: always
    networks:
      - app-network
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGOUSER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASS}
    volumes:
      - ./data/db:/data/db
networks:
  app-network:
    driver: bridge
